CuteOne/BadRotations

- .gitignore
- Rotations/Paladin/Protection/protectionPrettyBoy.lua
- misc.xml
Add your rotation to the misc.xml file and put them in the Rotations/Test folder and git will not track it. Making sync easier.
> Ease of use for test rotations

- Rotations/Mage/Frost/FrostLyLoLoq.lua
Changes to single target rotation for 7.2.5 update
With T20 2pc, Frozen Orb should be used as soon as it comes off CD.
Freezing Rain Blizzard. While the normal Blizzard action is usually enough, right after Frozen Orb the actor will be getting a lot of FoFs, which might delay Blizzard to the point where we miss out on Freezing Rain. Therefore, if we are not at a risk of overcapping on FoF, use Blizzard before using Ice Lance.
Winter's Chill from Flurry can apply to the spell cast right before (provided the travel time is long enough). This can be exploited to a great effect with Ebonbolt, Glacial Spike (which deal a lot of damage by themselves) and Frostbolt (as a guaranteed way to proc Frozen Veins and Chain Reaction). When using Glacial Spike, it is worth saving a Brain Freeze proc when …
> Massive changes to single target rotation and AOE rotation

- Rotations/Mage/Frost/FrostLemon.lua
- variable iv_start now checks at the very beginning of the call actions list rather than in the middle of the cooldowns lists.
- Blizzard AOE properly fixed. Now uses blizzard 2nd in the AOE Priority list without conditions.
- Flurry was instantly being casted as soon as the user started moving. Now Flurry follows the same conditions as the single target APL.
> Frost Mage: QOL Fixes

- Rotations/Mage/Frost/FrostLemon.lua
- Changes to 'While Moving' priority list to fix a dps loss in fights with a lot of movement.
- Frozen Orb now follows the Cooldown Toggle.
- Comet Storm has been added to the 'While Moving' priority list
- Blizzard will only attempt to cast if you're within 35 yards.
- Fixed weird interactions where blizzard would not be casted on enemies near walls therefore leaving the casting cursor on and pausing the rotation unless the user manually clicked a position. It will now cast blizzard on the targets true position rather than casting in the "best" position between multiple mobs.
- Removed Zann'esu Journey option, Rotation will now choose an optimal situation to cast Blizzard when players have this item equipped.
> Frost Mage: Moving Mode Changes

- Rotations/Warlock/Affliction/AfflictionFiskee.lua
- Rotations/Warlock/Destruction/DestructionFiskee.lua
- System/Core.lua
- System/Functions/Cast.lua
For some reason the queuecast function was placed after rotation in core. I think that if I queue up a cast, I want it to cast it next time.
Also it wasn't using the castSpell function, so would sometimes go in a loop, spamming the same action over and over.
> Make queue casting great again

- System/Functions/Misc.lua
- System/UI/Windows/Config.lua
- System/engines/EnemiesEngine.lua
- System/engines/EnemiesEngineFunctions.lua
Added check to make sure we don't waste ressources checking stuff that isn't a unit.
Only add lootable units to OM, if we have autoloot on.
Will now remove dead units from OM if they have no loot.
Will now only check isValidUnit in OM, if enemyListCheck is true, to save ressources.
Added Unit blacklist to OM (added the sharks)
Make isValidUnit not return nil, after whitelist was added
Removed TTD debug option, as it's perfect, and not needed anymore :)
> System - Performance updates WROOOM!

- System/engines/EnemiesEngineCollections.lua
Spells to be interrupted in Motherload (tested on key 11 intime)
> Whitelist Motherload

- System/engines/EnemiesEngineFunctions.lua
There is a unit in the list with no buff in nighthold mythic, this causes a nil error on the buff check.
> System - Fix nil error in safe damage

- Rotations/Warrior/Arms/ArmsCuteOne.lua
Should now use Mortal strike with 2 stacks of overpower and 2 stacks of executioners prescion or with 2 stacks overpower and talent deadnaught
> Mortal Strike in execute phase fix

- System/Lists/NoTouchUnits.lua
- System/engines/EnemiesEngineCollections.lua
- don't attack Champion of Light during Seal of Reckoning
- interrupt the heals for Forces of Light
- interrupt Apetagonize from the adds of Grong
- interrupt Jade Masters mage pyroblast
> Battle of Dazarlor, interrupts and notouch

- System/readers/combatlog.lua
Track player's casts only,
prevent compare number to nil errors for castTime.
> System - Queue Casted Fix.

- Rotations/Druid/Feral/FeralCuteOne.lua
Will now use Regrowth with 4 CP if rake is about to run out or Predatory Swiftness is about to run out.
> Feral - Fix for Regrowth

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
-  Font of Azshara (channel time 4 seconds)
-  later prepotions (6 seconds overall should be enough). 
_Not sure if the prepotions will cancel the trinket cast so correct me if it won't work._
- energy < 100 - we don't want to overlap the energy cap (could be even 80 not sure tho)
- combo >= 3 - to maximize elaborate planning talent
- cd.vendetta.remain() <= 14 - to combo it with vendetta (both trinket and vend has 2m CD)
> Font of Azshara

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
Ink does a big hit at 30%, it`s huge if it crits. Using coral with many stacks makes the chance to crit higher.
Pops coral at (30%-32%) and lasts for 20 seconds. Should be enough time to get the boss to lower than 30%. 31% would be the best but I don't know if the delay on the rotation could make it pop too late.
I rewrote my logics for trinkets so it matches the previous trinket logics from fiskee
> Logic for Razor Coral with Dribbing Ink

- Rotations/Druid/Feral/FeralCuteOne.lua
Won't break stealth anymore to proc bloodtalons which was bad for small pull timers (less than 6 seconds) as it causes you to open the fight without prowl buff.
> Don't break stealth for pre pull regrowth

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
- Rotations/Rogue/Outlaw/OutlawImmy.lua
- Hold Vendetta to combo it with Toxic Blade - max out DPS in Vendetta frame (line 849)
- Cast Toxic Blade when Master Assassin buff is over - on pull we prefer to use Mutilate in MA
- Cast Vanish when Toxic Blade is active - to avoid wasting MA crit for TB (line 856)
- Vanish essence checks with MA - Mainly for boss fights, we don't want to waste MA frame for GoA cast (line 882)
- Added missing cast for Tricks of Trade using trickUnit (old push)
> S0ul3r assa fixes

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
- System/Lists/InterruptWhitelist.lua
- **Worldvein Resonance** will be used on cooldown, out of master assassin crit buff - don't want to waste it in the opener
- **Vendetta and Toxic Blade** windows fixed - rotation will only do SIngle Target rotation when both or one of those are active on a target (made this change because of many adds in a new raid and we don't want to waste those debuffs for spreading DoTs on any other target than Boss). This only works when we have Master Assassin talent, I didn't test it for Subterfuge or Master Poisoner, so didn't want to fuck them up just in case.
> Assa_fixes

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
- Improved check for Razor Coral with Vendetta (Kkona)
- Better logic for Razor (I hope). It won't be reused when normal mobs are about to die, In M+ we want to kill target and use it on another one instead of reusing it on an almost dead target and having coral on CD.
- Added Reaping Flames (thanks @CuteOne)
> Razor fixes, Reaping Flames added, stealth improved

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
- System/Lists/Spells.lua
Added Worldvein buff to Spells.lua, need it for assa rota
Added Vanish, Cloak of shadows, Shadowmeld and blind for dealing with corruption.
Keep in mind that using Vanish/Shadowmeld is a huge DPS loss when it is used for something minor like avoiding Thing from beyond.
Added tweaks for raiding with Worldvein, it is being cast before Vendetta, so we don't lose time during its buff.
> Full corruption cloak support, more tweaks for assassination raiding

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
- # Crimson Tempest on multiple targets at 4+ CP when running out in 2-3s (based on target count) on any target
actions.dot+=/crimson_tempest,target_if=min:remains,if=spell_targets>3&remains<2+(spell_targets>=5)&combo_points>=4
- # Crimson Tempest on 1-3 multiple targets at 4+ CP when running out in 2s on any target
actions.dot+=/crimson_tempest,target_if=min:remains,if=spell_targets>1&spell_targets<4&remains<2&combo_points>=4
- # Crimson Tempest on ST if in pandemic and it will do less damage than Envenom due to TB/MA/TtK
actions.dot+=/crimson_tempest,if=spell_targets=1&combo_points>=(cp_max_spend-1)&refreshable&!exsanguinated&!debuff.toxic_blade.up&master_assassin_remains=0&!azerite.twist_the_knife.enabled&target.time_to_die-remains>4
> Assa better Crimson Tempest SimC

- System/Unlockers.lua
- System/engines/Tracker.lua
EWT hooks DX even in safe-mode, and you can enable this by using the secret command `enabledx` You'll notice this pull uses RunMacroText to enable this, this is because it's not listed in `IsHackEnabled` or `SetHackEnabled`
> Migrate Tracker Drawing to EWT DirectX Drawing

- System/UI/Windows/Config.lua
- System/engines/Tracker.lua
Turns out EWT saves this value locally. By running enabledx again, it will infact disabledx rather than enable. Because of this, it's best to just let the user know they need to run ".enabledx" themselves at least once, rather than try and enable this ourselves. I can speak with reliasn regarding adding this to the `IsCheatEnabled` `SetCheatEnabled` functions given by the EWT api, but for now this change is the better option.
> Remove auto enabling of enabledx in the Tracker due to EWT saving this value.

- System/Lists/Spells.lua
Warlock Shared - Covenant Abilities copied to debuffs.
> Warlock Shared

- Rotations/Druid/Balance/BalanceLaksmackt.lua
- Rotations/Druid/Restoration/RestoLaksmackt.lua
Added an extra option to use the Mount form as ground mount instead of the Travel form.
[Mount Form](https://www.wowhead.com/spell=210053/mount-form)
[Travel Form](https://www.wowhead.com/spell=783/travel-form)
I think this is usefull for playing together with a friend.
Thank you :D
> Added Mount Form Druid

- Rotations/Warlock/Affliction/AfflictionKink.lua
- Rotations/Warlock/Demonology/DemonologyKink.lua
KinkAffliction | Version 2.0.8
-------------------------------------------
-- [Beta] | Added Dark Soul toggle button w/ 4 modes. 
--- With Darkglare] (Raid, target dummy, etc)
--- [With Cooldowns] (Controllable through cooldowns toggle)
--- [With TTD] (Mythics, soloing, torghast, etc)
--- [With Hotkeys] (Disables Auto DS, only able to be used w/ hotkey)
-- Changed default Seed of corruption targets value to 6. 
-- Added "PS TTD" under Vile Taint TTD in the Offensive tab. 
-- Fixed pet target issues.
> KinkAffliction | Version 2.0.8

- Rotations/Druid/Feral/FeralCuteOne.lua
Predator talent usage on energy deficit, use it when possible. Buff overlap doesn't matter much, we're here for TF Energy.
Ferocious Bites is still free on Clear Casting but extra dmg is still used based on free energy
> Feral - Predator and FB tweaks

- Rotations/Druid/Restoration/RestoAura.lua
Rotation hangs on Nature's Swiftness invalid target. NS must be cast on "player" only.
> RestoAura - NS doesn't need unit

- Rotations/Druid/Feral/FeralCuteOne.lua
- System/Lists/Spells.lua
Night Fae Covenant Convoke and Feral Talent Convoke overlap or is replaced with latter one. Different spell IDs and cooldowns. In some cases rotation tries to cast wrong one and hangs. No point taking this talent with Night Fae. Mostly pre-patch issue.
> Feral covenant vs talent Convoke

- System/Lists/Spells.lua
I think they changed this late 2022/early 2023:
> DK has Empower Rune Weapon as core DK talent
