CuteOne/BadRotations

- Rotations/Mage/Frost/FrostCuteOne.lua
WowHead rotation for Single target under a DBT APL. Talents = 3222121
> added DBT APL (based off wowhead rotation)

- Rotations/Mage/Frost/FrostCuteOne.lua
Support for Incanter's Flow, Ray of frost, GlacialSpike, Ice Nova, Comet Storm
> Added more talents support in DBT APL

- Rotations/Mage/Frost/FrostCuteOne.lua
Better Rune of Power usage, better Flurry Logic, code clean up
> DBT APL improvements

- Rotations/Mage/Frost/FrostCuteOne.lua
Needs better logic. But working
> Frost Bomb working.

- Rotations/idList.lua
> Frost Mage ID update

- Rotations/Mage/Frost/FrostCuteOne.lua
Unified to AMR APL in DBT APL, Code cleanup
> Dbt APL clean up.

- Rotations/Warlock/Destruction/DestructionCuteOne.lua
Fixed rotation not picking up on immolate debuff and spamming it only
> Immolate bug fix

- Rotations/Paladin/Protection/protectionPrettyBoy.lua
- Rotations/idList.lua
Included CuteOne's taunt manager from the bearz. Added in GoAK and
Ardent Defender. Fixed issue with
> Updated Prot rotation and prot buff id's

- Rotations/Demon Hunter/Havoc/HavocCuteOne.lua
- Rotations/Mage/Arcane/ArcaneDBT.lua
- Rotations/Mage/Fire/FireCuteOne.lua
- Rotations/Mage/Frost/FrostCuteOne.lua
- Rotations/Monk/Mistweaver/MistweaverLyLoLoq.lua
- Rotations/Priest/Shadow/ShadowCpoworks.lua
- Rotations/Shaman/Elemental/ElementalCuteOne.lua
- Rotations/Warlock/Affliction/AfflictionCuteOne.lua
- Rotations/Warlock/Demonology/DemonologyCuteOne.lua
- Rotations/Warlock/Destruction/DestructionCuteOne.lua
Added new options on MW Monk routine
Correction of Essence Font to not spam cast
Correction of race comparision
> Monk Stuff

- System/engines/HealingEngineCollections.lua
Fix novaEngineTables.skipNPC using Kuukuu latest fix
> Fix novaEngineTables.skipNPC using Kuukuu latest fix

- Rotations/Monk/Brewmaster/BrewmasterKuukuu.lua
> For Kuukuu

- Rotations/Priest/Discipline/DisciplineBizkut.lua
Fix PTW/SWP buff count at a time
> Fix PTW/SWP buff count at a time

- Rotations/Priest/Discipline/DisciplineBizkut.lua
Added mass dispel @ cursor functionality - taken from the Holy priest rotation. Modified slightly to only cast when not moving, otherwise it tries spamming it whilst moving.
> [Priest][Disc] Added mass dispel utility

- Rotations/Priest/Discipline/DisciplineBizkut.lua
- Rotations/idList.lua
Fix SM logic add Plea for debuff
Fix SM logic to use Plea if moving
Fix Schism and Penance logic  when moving
Add minimum Atonement option to damage dealer spells
Fix LW CD order and Schism buff check
Fix Rapture in 5man
> Fix SM logic add Plea for debuff

- Rotations/Priest/Discipline/DisciplineBizkut.lua
- System/engines/EnemiesEngineCollections.lua
Add Gul'dan to doNotTouchUnitCandidates
Add player to PWS logic
Fix cast PWS on TANK or anyone without Atonement only
Add Grace talent downstream
Don't attack Shimmering Manaspine
PWR in combat only
Add Dispel Magic
> Add Gul'dan to doNotTouchUnitCandidates

- Rotations/Druid/Restoration/RestorationSvs.lua
> user free mana when innervate

- Custom/Functions.lua
- Rotations/Druid/Restoration/RestorationSvs.lua
- Rotations/idList.lua
> Resto Druid Changes by Fengshen

- Rotations/Priest/Discipline/DisciplineBizkut.lua
Add Interrupt options
Fix Debuff SM
Fix PTW
Fix Penance
Add Interrupt button
> Disc Priest: Add Interrupt options

- Rotations/Priest/Discipline/DisciplineBizkut.lua
Innervate will use PWR
Estel optimize
Power of Of Dark Side buff check
Angelic Feather and Body and Soul can be casted in combat
Interrupt Typo
> Disc Priest: Add Pre-pull Opener with DBM timer

- Rotations/Priest/Discipline/DisciplineBizkut.lua
Disc Priest: Support Norgannon's Foresight legendary feet. Need feedback
Disc Priest: Rapture out of Atonement rotation
Disc Priest: Fix OOC to include Grievous Wound and Grievous Rip
Disc Priest: SM emergency check fix
Disc Priest: Fix Schism target
Disc Priest: Add Mass Dispel when Purify in CD
> Disc Priest: Support Norgannon's Foresight legendary feet. Need feedback

- Rotations/Monk/Mistweaver/MistweaverLyLoLoq.lua
Added logic for dispell in second boss of ToS.
> Mistweaver - Gnawed Thumb Ring. TFT + Essence Font. Pull Timer added

- Rotations/idList.lua
add frost mage T20 2pc buff frozen mass to table
> add frost mage T20 2pc buff frozen mass to table

- Rotations/Mage/Frost/FrostLyLoLoq.lua
> Fixed hard casting flurry

- BadRotations.toc
- README.md
- Rotations/Mage/Frost/FrostLemon.lua
- Rotations/Mage/Frost/FrostLyLoLoq.lua
Added separate category for all items.
Trinkets on use have been added. There are now three options to choose from. 
On cooldown, On Boss Health, On Self Health. 
You can specify a value when to use each trinket. The on cooldown option will ignore the value and use the trinket whenever available.
> Frost Mage: Items, Trinkets, Racials, Fixes and Name Changes

- BadRotations.toc
- README.md
- Rotations/Warrior/Arms/ArmsLemon
Testing new Single and Execute Priority. Modified off of CuteOnes Arms profile.
> Arms Warrior: New Profile Testing New Single/Execute Priority. 

- Rotations/Warrior/Arms/ArmsLemon.lua
> Arms Warrior: Small Fixes and changes

- README.md
- Rotations/Monk/Mistweaver/MistweaverLyLoLoq.lua
* Update Readme
* Added option to enable/disable RSK
* Try to fix EM being casted two times in a row.
> MW - update Dispel, minor changes

- Rotations/Warrior/Arms/ArmsLemon.lua
- Fixed Artifact weapon not casting
- Fixed Whirlwind not casting causing high amounts of unspent rage
- Fixed Bladestorm not casting
> Arms Warrior: Big fixes

- Rotations/Mage/Frost/FrostLemon.lua
Frost Mage: Logic Change, Blizzard Revert
> Frost Mage: Logic Change, Blizzard Revert

- README.md
- Rotations/Monk/Mistweaver/MistweaverLyLoLoq.lua
- Rotations/idList.lua
- T20 4p Buff
- Check added for Spinning Crane Kick
- Some optimization
> MW - T20 logic, improve Pre-pull logic.

- Rotations/Mage/Frost/FrostLemon.lua
Frozen Orb now has its own toggle.
> Frost Mage: Frozen Orb Toggle

- Rotations/Death Knight/Unholy/UnholyLemon.lua
- Rotations/idList.lua
- Wrong ID for cold heart
- Added debug info
- Fixed Dark Transformation
> Unholy DK: Big fixes

- Rotations/Death Knight/Unholy/UnholyLemon.lua
- Rotations/idList.lua
- Actionlist_Generic was not calling properly
> Quick Unholy DK Fix

- Rotations/Death Knight/Unholy/UnholyLemon.lua
- Better Targetting, Pet Management.
> Unholy DK: Better Targetting, Pet Management

- BadRotations.toc
- Rotations/Priest/Holy/HolyOdan.lua
Added kj trinket, binding heal(in progress), 3 renew options and quaking
support.
> Odan's holy rotation edit of svs

- Rotations/Druid/Restoration/RestorationSvs.lua
Routine pauses when drinking a Leytorrent Potion
> Added Leytorrent Logic

- Rotations/Monk/Brewmaster/BrewmasterPanglo.lua
> Typo Fixes

- Rotations/Demon Hunter/Vengeance/VengeanceCuteOne.lua
- System/Functions/Cast.lua
- System/Functions/Spell.lua
- System/engines/Interrupts.lua
- System/engines/InterruptsFrame.lua
- System/engines/InterruptsFrame.txt
Patch 8.0.1 (2018-07-17): Removed the second parameter, "nameSubtext". Second parameter is now "text" (former third parameter).
> UnitCastingInfo & UnitChannelInfo fixes

- System/Functions/Combat.lua
> One more check - for ToS bosses

- Rotations/Priest/Shadow/ShadowJR.lua
> shadow typo fix and buffcheck

- System/Lists/Spells.lua
Update Ebonbolt from Artifact Trait to Talent ID (214634 to 257537)
> Update Spell IDs

- Rotations/Rogue/Subtlety/SubtletyCuteOne.lua
Reverts CuteOne/BadRotations#274
Code added without permission
> Revert "This is good."

- Rotations/Rogue/Subtlety/SubtletyCuteOne.lua
- No more Def. GCD in SD functional again
- CS added to Interrupts
> Forgot to add this back in after the revert.

- System/Lists/Spells.lua
Updated SoothingMist cast ID for Mistweaver
> Spells.lua

- Rotations/Monk/Mistweaver/Mistweaver_Ledecky.lua
-Still based off CpoWorks rotation. Just added some additional features and will continue to do so over time
-Updated the profile as needed after running a few mythic dungeons. 
-Added Options for DPS and Detox mode Enable/Disable
-Added Summon Jade Serpernt options
-Added a fix for using Jade Statue. I might need some help with this as having the statue out will break the rotation after a couple of intervals. For now i've added a workaround that will make it continue to work as long as it switches the soothing mist targets. Full details of problem commented inside rotation
> Mistweaver_Ledecky.lua

- Rotations/Priest/Holy/HolyOdan.lua
-Restores Original File for HolyOdan for those who still prefer to use this profile before I've made changes to it.
> HolyOdan.lua

- Rotations/Priest/Holy/HolyLedecky
-Adds my profile based off of HolyOdan. 
-Adds additional options as well as fixes rotation priorities.
-Will continue to work on this provide updates.
> HolyLedecky.lua

- System/Lists/LineOfSight.lua
If not working blame [US] Imdasandman
> Possible fir for Taloc LoS issues.

- Rotations/Priest/Holy/HolyLedecky.lua
-Fixed issue with Flash Heal On Me that ignored settings. Should now work.
-Added Apotheosis Mode useful for mythic plus. Not tested.
> Some fixed and added Apotheosis Mode

- Rotations/Monk/Mistweaver/Mistweaver_Ledecky.lua
-Fixed Local mana that was causing issues for mana checks. Should now properly work for some options like Essence Font Minimum Mana
-Fixed Detox. Should now work properly.
> fixed local mana added some stuff

- Rotations/Priest/Holy/HolyLedecky.lua
-Fixed issue with a check for having Apotheosis Buff
> fixed apotheosis mode not working

- Rotations/Priest/Holy/HolyLedecky.lua
-Fixed Purify only casted on self.
-Fixed Purify ignoring the toggle buttons
-Reworked HW Sanctify using JR's code. Thank you. (However, in very large raids, it is possible that your WoW may freeze for up to 4 seconds because of the coding scanning so many players. However, works dam better than the old coding.
-Updated some Binding Heal Logic
> some fixes

- Rotations/Monk/Mistweaver/Mistweaver_Ledecky.lua
-Fixed Mana check on Essence Font
-Added option for using Soothing Mist before casting EM or Vivify
> fixed mana check on EF

- Rotations/Priest/Holy/HolyLedecky.lua
-Added option for use of the old coding for HW Sanctify where it won't freeze your WoW. However, it will be less effective than the current coding,
> Holy - Added option for old HW Sanctify

- Rotations/Priest/Holy/HolyLedecky.lua
-Fixed Binding Heal not working properly after recent update
-Added back option of using Binding Heal with single target rather than wait for at least 2 injured party.
-Added support for Revitalizing Voodoo Trinket
> Holy - some fixes and added options

- System/Functions/Aura.lua
- System/UI/Windows/Config.lua
- System/engines/EnemiesEngine.lua
and tiny change to dynamic target threat
> System - Dispel delay changed to seconds

- Rotations/Monk/Mistweaver/Mistweaver_Ledecky.lua
-Added back Upwelling Talent Support again, but needs testing and feedback
-Added Revitalizing Voodoo Trinket SUpport
-Added support for not casting EF when QUaking Debuff is on you for mythic+
> MW added Upwelling support again

- Rotations/Priest/Holy/HolyLedecky.lua
-Fixed Renew not properly working.
-Added renew limit support to Renew while moving
-Fixed Binding Heal Multi giving errors.
> Holy - some fixes

- Rotations/Hunter/BeastMastery/BeastmasterDastano.lua
Note: Dispel Delay in Heal Engine is important. Set it to 0.5 or 1 for a fast Dispell.
> Fixed Purge

- Rotations/Hunter/BeastMastery/BeastmasterDastano.lua
Fixed Purge : **Remember**, Delay is setup in Heal Engine
Fixed Pre-Pull without Potion: Had a typo here, now it should work. 
Fixed Dash Failcasts: Nothing you should noticed, but it anoyed me, so now it should work.
> Fixed Purge, Fixed Pre-Pull without Potion, fixed Dash Failcasts

- Rotations/Priest/Holy/HolyLedecky.lua
added options for timing Angelic Feather & Body and Mind
> Update HolyPriest - options for movement spells

- Rotations/Priest/Holy/HolyLedecky.lua
option to disable player hp check for binding heal
> Update HolyPriest - option to disable player hp check for binding heal

- Rotations/Monk/Mistweaver/Mistweaver_Ledecky.lua
MW -added a option to use Enveloping Mist on Tanks only. Not tested.
> MW - added EM Tanks Only

- Rotations/Monk/Mistweaver/Mistweaver_Ledecky.lua
used checks for talent instead of some checkboxs.
> reworked EF Upwelling checks

- System/Functions/Misc.lua
- System/engines/EnemiesEngineFunctions.lua
We already run enemyListCheck on all units that are added to br.units, so lets check that first, before wasting ressources on another enemyListCheck
> System - No more checking just to check

- System/engines/EnemiesEngine.lua
- System/engines/EnemiesEngineFunctions.lua
- System/engines/ttdTable.lua
For easier inspection in table explorer
> System - Moving unitSetup to br namespace

- System/Loader/cCharacter.lua
> Flask id, flask buff id, clean up

- Rotations/Rogue/Assassination/AssassinationImmy.lua
- System/Lists/Dummy.lua
- System/Lists/Spells.lua
- System/Loader/cBuilder.lua
- System/readers/combatlog.lua
> rogue stuff

- Rotations/Priest/Holy/HolyLedecky.lua
i think a fix for renew while moving.
> fix renew while moving

- Rotations/Hunter/BeastMastery/BeastmasterCuteOne.lua
- Rotations/Hunter/Marksmanship/MarksmanshipCuteOneArhTest.lua
BM Killcommand execute
MM smaller cast window at execute
> Add bugs to fix later

- Rotations/Warlock/Destruction/DestructionFiskee.lua
- System/engines/EnemiesEngine.lua
Only with enhanced TTD enabled
> TTD - Fixed Mother TTD calc

- Rotations/Warrior/Arms/ArmsCuteOne.lua
Hopefully this fix the problem people have been report about whirlwind on 1 target
> Whirlwind 2 targets fix

- System/engines/EnemiesEngineCollections.lua
Didn't think there was any change to consume-essence from pack before boss and the ones on the boss but there is.
> Let's interrupt on last boss to!

- System/Functions/Aura.lua
> System - Fix debuff checking

- System/engines/EnemiesEngineCollections.lua
Not 100% finished but should still be better than default.
> Whitelist - Underrot

- System/engines/EnemiesEngineCollections.lua
> More whitelist stuff

- Rotations/Priest/Holy/HolyLedecky.lua
Circle of Healing added,
Amended Aoe Healing priority
> Circle of Healing addition

- Rotations/Priest/Holy/HolyLedecky.lua
Added Checkbox for use of Potion of Replenishment
> Potion of Replenishment Addition

- Rotations/Demon Hunter/Havoc/HavocCuteOne.lua
- Rotations/Druid/Balance/ReyneBalance.lua
- Rotations/Druid/Feral/FeralCuteOne.lua
- Rotations/Druid/Guardian/GuardianPanglo.lua
- Rotations/Hunter/BeastMastery/BeastmasterDastano.lua
- Rotations/Hunter/Marksmanship/MarksmanshipCuteOneArhTest.lua
- Rotations/Hunter/Survival/SurvivalCuteOne.lua
- Rotations/Mage/Arcane/ReyneArcane.lua
- Rotations/Mage/Fire/FireWinston.lua
- Rotations/Rogue/Assassination/AssassinationCuteOne.lua
- Rotations/Rogue/Assassination/AssassinationFiskee.lua
- Rotations/Rogue/Assassination/AssassinationImmy.lua
- Rotations/Rogue/Outlaw/OutlawImmy.lua
- Rotations/Rogue/Subtlety/SubtletyCuteOne.lua
- Rotations/Shaman/Enhancement/EnhancementCuteOne.lua
- Rotations/Warlock/Affliction/AfflictionFiskee.lua
- Rotations/Warlock/Destruction/DestructionFiskee.lua
- Rotations/Warrior/Arms/ArmsCuteOne.lua
- System/Loader/cBuilder.lua
- System/readers/common.lua
Format is now .active and .rank, instead of .active() and .rank(), no more function calling
> System - Change to trait reader

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
> Assa - Option to FoK/CT blacklisted units

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
- Rotations/Rogue/Subtlety/SubtletyFiskee.lua
Allow tricks to be casted on tank
> Sub/Assa - Tricks update

- System/engines/EnemiesEngineCollections.lua
- Tidal Empowerment, Brother Joseph , Stormwall Blockade encounter
- Storm's Empowerment, Sister Katherine , Stormwall Blockade encounter
- Howling Winds, Lady Jaina Proudmoore
> added Interrupts to Whitelist:

- System/engines/EnemiesEngineCollections.lua
Just took the DBM interrupt warnings and copy it to BR interruptlist ;)
> Updated Interruptlist for Dungeon Trash, straight out of DBM

- System/Core.lua
- System/engines/EnemiesEngine.lua
- System/engines/EnemiesEngineCollections.lua
- System/engines/EnemiesEngineFunctions.lua
Faster loading of enemies, smarter usage of ressources, splitting unit testing into more frames, for smoother gameplay. It's not a FPS increase, but should result in better experience for users
> System - New OM function for EWT users

- Rotations/Priest/Shadow/AHshadow.lua
- System/Lists/Spells.lua
No deletes inside the Spells.lua, only additions. Also, AHshadow, is now a thing for BR!
> My Shadow Priest added, including additions within the Spells.lua.

- Rotations/Priest/Shadow/AHshadow.lua
Updated VT and SWP Checks.
Added Healthstones.
Should now return better uptime on both debuffs.
> Healthstones, VT & SWP checks.

- Rotations/Priest/Shadow/AHshadow.lua
Some updates to cooldown usage, and priority system updated.
Removed some optional things aswell, to make the rotation more fluid.
> Priority Update

- Rotations/Priest/Shadow/AHshadow.lua
Fisker made me aware of Function issue.
> Added changes

- Rotations/Priest/Shadow/AHshadow.lua
Should be fixed now, mis type error.
> Interrupting

- Rotations/Priest/Shadow/AHshadow.lua
Misery talent is now a thing, with AHshadow!
> Misery Update.

- Rotations/Priest/Shadow/AHshadow.lua
Full Cast Mind Sear on Thought Harvester buff.
Added a check for in Combat for Defensives, so it doesn't use it outside of combat.
Few Misery updates aswell.
> Full Cast Mind Sear

- Rotations/Priest/Shadow/AHshadow.lua
> Cooldowns Mode

- Rotations/Paladin/Holy/HolyLaksmackt.lua
> Added heal logic support for Grieveous wound

- Rotations/Paladin/Holy/HolyLaksmackt.lua
added a trinket and added a small dps fix
> Hpally update

- Rotations/Rogue/Assassination/AssassinationImmy.lua
- Rotations/Rogue/Outlaw/OutlawImmy.lua
- System/Lists/Spells.lua
> Assassination/Outlaw - Immy

- Rotations/Paladin/Holy/HolyLaksmackt.lua
Added random option to LoH (request)
Added support for Avenging Crusader
Standardized Trinket support (sorry!)
Added Judgment heal options (kept DPS)
Rewrote Holy Shock Mastery logic (should feel no changes)
> Hpally utility update

- Rotations/Paladin/Holy/HolyLaksmackt.lua
> Glimmerbug

- Rotations/Mage/Frost/FrostReyne.lua
works a little better with glacial spike
made by Abo from discord
( not a developer so it might be errors )
> Ice lance while moving, little shatter logic. trinkets  added

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
> Assassination Pool Party

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
Added small delay to auto target of explosive
> Assa - No so fast sir

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
@fiskee
The same ID issue as for out of combat restealth.
> *Restealth if enemy in combat. *Blindside conditions.

- Rotations/Druid/Feral/FeralCuteOne.lua
Updated Potions
Added dropdown menu to potions
Fixed potions (will now use the one you selected on pre pull and with cooldowns if ttd is > 45 sec)
(Note: Superior Battle Potions will only be used in raids, others also in group)
Added a option to use Berserk and Tiger's Fury pre pull
It should now always use Thrash
> Feral Druid Update

- Rotations/Mage/Fire/FireWinstonv8.lua
pre-pull
pre-pots
focused beam
cyclotronic blast
hyperthread wrists
Shiver Venom Relic
and weird stalls / bugs fixes
> updates updates updates

- Rotations/Demon Hunter/Havoc/HavocCuteOne.lua
- System/engines/EnemiesEngineCollections.lua
Purgeable list update
Havor Purge all
> Dungeon Magic Purge Update

- Rotations/Priest/Shadow/Panglo_Chad_ow.lua
Added moving SW:P checkbox option
Added moving shadow crash
Removed requirement to stand still while casting Focused Azerite Beam
Code Cleanup a la Fiskee
> Panglo spriest edits for lulz

- Rotations/Mage/Fire/FirePsy.lua
Made my own profile based on AMR and a few things pulled from existing sources.  First time making a profile so hopefully it's alright.
> FirePsy - FIre mage profile

- Rotations/Mage/Fire/FirePsy.lua
Don't use meteor without RoP/ better support for Font on prepull
> Meteor/Font Fix

- Rotations/Rogue/Outlaw/OutlawImmy.lua
**Added logic for:** 
- Razor Coral,
- Razor Coral + Dribbling Inkpod,
- Blood of the Enemy essence.
**Added fix for dismount when mounted and not flying **
> Coral logic, dismount fix, Blood essence logic

- Rotations/Rogue/Outlaw/OutlawImmy.lua
- Added disable/enable button for Essences
- Tweaks for razor coral usage
> Further fixes for coral/essences

- Rotations/Rogue/Outlaw/OutlawImmy.lua
Essences UI
BotE logic - use before Between the eyes
More logic to blade Flurry
> UI, new BotE logic, flurry additional logic

- Rotations/Rogue/Outlaw/OutlawImmy.lua
- Added auto Tricks of Trade on focus/tank - taken from assassination rogue
- Added new reroll logics
- Updated auto HS/health pot function
- More Razor Coral logic/prevent casts
- Some minor fixes
> Fixes for immy's outlaw 

- Rotations/Rogue/Outlaw/OutlawImmy.lua
- Rotations/Warrior/Fury/FuryPang.lua
Added Guardian of Azeroth usage only for bosses
> Essence tweaks, added more essences and UI (Outlaw rog), GoA a for boss (Fury warr)

- Rotations/Death Knight/Unholy/UnholyCuteOne.lua
- Rotations/Druid/Restoration/RestoAura.lua
Was causing lua error and not casting Starsurge when Balance Affinity is talented
> Fixed "Starsurge" spell name & Unholy Tweaks

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
Autostealthing on 25 yards for safety (15 yards previously which is an aggro range), typo fix
> Fix autoStealth

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
Some fixes from simc/logs for opener logic
> Adjustments for opener on Bosses

- Rotations/Warrior/Arms/ArmsCuteOne.lua
- Added Essences support
- Removed all Colossus Smash cds check from rotation
- Tweaked Warbreaker and Sweeping Strikes to cast on bosses (ST)
- Tweaked Heroic Leap Key
- Added Storm Bolt logic (Dungeons) - Copied from Panglo's Prot CR
- Tweaked Trinkets and added Ashvane's Razor Coral logic
- Removed unnecessary stuff
> Added essences support and Tweaked profile

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
- Added poisoned knife cast when out of range 
- Vanish removed from the BR menu and added as a UI toggle
> Dem_Changes

- System/Lists/NoTouchUnits.lua
Added Eye of Chaos to noTouchUnits
> HV Eye of Chaos noTouchUnits

- Rotations/Rogue/Outlaw/OutlawImmy.lua
cooldowntoggle for auto/on/off
groupttd for bladeflurry
> cooldowntoggle, blade flurry ttd

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
- Added corruption cape support
- Type fix in coral code
- Added Exposed Synapse to burn units (we don't want to waste Rupture on it)
> Corruption cape support, typo fix

- Rotations/Warrior/Fury/FuryPang.lua
- Checkbox for fear
- Fix for Reaping Snipe
> Fury tweaks

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
- Trying to fix blinding Thing from beyond
- BotE is casted properly when we are using Toxic Blade talent (after using TB)
- Fix for rotations pausing after using vanish with Subterfuge talent (needs testing still, not sure if this is the best way to fix it. I wasn't touching code for Subterfuge at all so I am not 100% sure what is where :P)
> Assassination Tweaks

- Rotations/Mage/Fire/FireWinstonv8.lua
> latest firemage profile

- Rotations/Mage/Fire/FireWinstonv8.lua
added the obsidian claw trinket to the list
> clawtrinket added

- Rotations/Druid/Guardian/GuardianADSpirit.lua
- Rotations/Paladin/Retribution/RetributionADSpirit.lua
- System/Lists/CCUnits.lua
- Ret CR
- Updated ccUnits list
- Updated Guardian CR
> COVID-19 vibes

- Rotations/Rogue/Assassination/AssassinationFiskee.lua
Subterfuge should work now 100%, tested it a bit now and was gucci.
> Giga Reaping Flames, Subterfuge tweaks

- System/Lists/Spells.lua
Added Malefic Grasp 1/2 (fix alphab oder), and add VileTaint Debuff
> Warlock Spells Addition

- Rotations/Shaman/Enhancement/EnhancementAura.lua
Small adjustments to make enhancement work with new SL changes
> Small update to make enhancement work

- System/Lists/Spells.lua
> tiny fix for enhancement talent

- System/Lists/Spells.lua
> now its fine

- Rotations/Shaman/Enhancement/EnhancementAura.lua
small change with frostbrand being in the way
> begone frostbrand

- Rotations/Demon Hunter/Havoc/HavocCuteOne.lua
- Inner Demon Buff Check 
- Blade Dance Variable Change (Blade dance even when talented into Cycle of Hatred)
> Minor Update HavocCuteOne.lua

- Rotations/Paladin/Holy/HolyLaksmackt.lua
- System/Lists/Spells.lua
Updated hpala to a working state. Tested in raids.
> Update holy Spells / Pala rota

- Rotations/Shaman/Enhancement/EnhancementAura.lua
added flameshock spread, cleanup of none existing spells and removed class power
> Enhancement Aura improvement

- Rotations/Shaman/Restoration/DumpuResto.lua
Its barebones but was good enough to heal heroic bfa dungeons. I know theres so much more that can be done to make it better, it will get there lol
> Damply's Resto Shaman WIP

- Rotations/Warrior/Fury/FuryPang.lua
* Prevent attempting to charge unless More than 8 Yards and Less than 25
* Adds Onslaught to rotation
> Adds Onslaught to Fury rotation and fix charge

- Rotations/Warrior/Fury/FuryPang.lua
- System/Lists/Spells.lua
-removed corruption handling
-removed howl (didnt do anything)
-added piercing howl as a defensive (slows enemies so you can run like a little girl)
-added ignore pain
-removed razor coral support (anyone still using this?)
-removed m+ section from profile (pigcatcher is core now and bursting wasnt doing anything)
> cleanup fury

- Rotations/Paladin/Holy/HolyLaksmackt.lua
SoTR + DP
Holy shock GCD Checker for LOD/WoG
> Various optimisations

- BadRotations.toc
- System/SlashCommands.lua
- System/UI/Windows/Config.lua
- System/Unlockers.lua
- System/Updater.lua
Enabled from settings and requires EWT. Talks to a web api to print the latest changes in-game when user is outdated.
Phase 1 of 2.
> Auto Check for Updates

- System/Lists/Items.lua
Darkmoon Deck: Putrescence (AoE:Use trinket) | Items
> Darkmoon Deck: Putrescence | Items

- Rotations/Warlock/Affliction/AfflictionKink.lua
AfflictionKink | Version 1.6.5
-- More edits, priority changes, etc. 
-- Created a pull request for dark moon trinket, once it's added to items I'll add AoE support for it.
> AfflictionKink | Ver 1.6.5

- Rotations/Warlock/Demonology/DemonologyKink.lua
KinkyDemo(Fiskee) | Version 1.0.0
-- Added axe toss interrupt (Keunny), added spell queue ready, covenant abilities.
> KinkyDemo(Fiskee) | Version 1.0.0

- Rotations/Shaman/Enhancement/EnhancementCuteOne.lua
Just for people who want to control windfury totem for doom winds burst
> Manual windfury totem key

- Rotations/Warlock/Affliction/AfflictionKink.lua
AfflictionKink | Version 1.6.9
> AfflictionKink | Version 1.6.9

- Rotations/Warlock/Demonology/DemonologyKink.lua
> KinkySpirit | Version 1.1.0

- System/UI/Elements/ScrollingEditBox.lua
> System: Add outline to edit box to be more user friendly

- Rotations/Hunter/Marksmanship/MarksmanshipCuteOne.lua
no rapid fire and whatnot cancels
> MD while casting fix

- System/Loader/cCharacter.lua
> Fix Ignore Combat option

- Rotations/Monk/Mistweaver/MistweaverLylo.lua
Changelog:
- Add Touch Of Death Mode
- Add Weapons of Order options
- Add support to Tigers Lust
- Edit some debug stuff
- Fix AOE Enveloping Breath
- Add Healing Out Of Combat
> Mistweaver Monk - Release version 1.3.0

- Rotations/Monk/Mistweaver/MistweaverLylo.lua
> Mistweaver Monk - Hotfix count table

- System/Lists/BurnUnits.lua
- System/Lists/InterruptWhitelist.lua
Adding adds for first two boss fights and frostbolt volley interrupt on the mages for the second boss fight.
> Adding Nectrotic Wake Burns and Interrupts

- Rotations/Warlock/Affliction/AfflictionKink.lua
-- Changed ST spells priority
-- Fixed multi-dotting
-- Added Fear Unit List with toggle (Experimental)
-- Fixed Pre-Pull Timer
-- General tweaks
> KinkAffliction | Version 1.7.9

- Rotations/Warlock/Affliction/AfflictionKink.lua
- System/Lists/Pets.lua
-- Separate DS clip for ST and AoE
-- Lesser Drain Soul clipping in ST (More ticks = more DPS)
-- Berserking (Troll) will cast with both Darkglare and Darksoul.M
-- Pets attacks are more aggressive now
-- Updated pet ids in Pets list
>  AfflictionKink | Version 1.8.0

- Rotations/Warlock/Demonology/DemonologyKink.lua
DemonologyKink | Version 1.3.1
> DemonologyKink | Version 1.3.1

- Rotations/Warlock/Demonology/DemonologyKink.lua
DemonologyKink | Version 1.3.2
-- fix for spamming soul strike if you have a pet other than felguard out.
> DemonologyKink | Version 1.3.2

- Rotations/Monk/Mistweaver/MistweaverLylo.lua
> Monk Mistweaver 2.0.1

- Rotations/Warlock/Affliction/AfflictionKink.lua
-- Removed non-working options
-- Added flask, trinkets and basic healing modules
-- Added Drain Soul Snipe for both ST and AoE modes
-- Much more Enhanced AoE
-- Moved Toggle options to Lists/Toggle Options tab
-- Added support for leveling
-- General tweaks and cleanup
> AfflictionKink | Version 1.8.2

- Rotations/Druid/Restoration/RestoLaksmackt.lua
litte fix for Mount Form and Auto Form added. Requested and tested by mrJones2k#2881
>  fix for Mount Form and Auto Form added

- Rotations/Warlock/Affliction/AfflictionKink.lua
-- CR will now hold PS for SR (Night Fae)
-- Added forced dots refresh option before casting PS
-- Some Tweaks
> AfflictionKink | Version 1.8.3

- Rotations/Monk/Mistweaver/MistweaverLylo.lua
- System/Lists/Spells.lua
Add support to Ancient Teachings of the Monastery
> Mistweaver Monk 2.2.0

- Rotations/Warlock/Affliction/AfflictionKink.lua
> AfflictionKink | Version 1.8.4

- Rotations/Hunter/Marksmanship/BigMarksmanship.lua
- System/Functions/Custom.lua
- System/Functions/Misc.lua
- System/Lists/Items.lua
- System/Lists/Maps.lua
Added interrupts
Corrected cc logic
Fixed prepull actions
Add the actual functions for healing
> Fix trinket == nil (Move everything profile level)

- Rotations/Hunter/Marksmanship/BigMarksmanship.lua
Fix "Interrupt All" -option, possible (didnt test)
Use cooldowns with trueshot
MD logic into pre-pull
> Fix explosive shot and rapid fire,

- Rotations/Warlock/Affliction/AfflictionKink.lua
-- Implemented debuff.refreshCount() API
-- No more falling dots in both ST and AOE (maybe =P)
-- Added checkbox for Phantom of Singularity and Soul Rot
-- More tweaks
> AfflictionKink | Version 1.8.5

- Rotations/Monk/Mistweaver/MistweaverLylo.lua
Removed settings from rotation.
Use from BR.
> Mistweaver Monk Fix - 2.2.2

- Rotations/Mage/Frost/FrostKink.lua
-- Updated Single Target, AoE, Cooldowns and movement SimC APLs. 
This is a test build, please report any bugs, errors or things that are being handled wrong, thank you.
> Shadowlands FrostKink Update | 1.2.1

- Rotations/Rogue/Subtlety/SubS0ul.lua
- System/Lists/BurnUnits.lua
- System/Lists/NoTouchUnits.lua
Tweaks for mythic council, Find weakness for raiding, avoid some units
Burn attendants, avoid bosses with immunity shields
> Tweaks for mythic council, Find weakness for raiding, avoid some units, lists update

- Rotations/Warlock/Affliction/AfflictionKink.lua
> Test PR Affliction 2.0.3

- Rotations/Warlock/Affliction/AfflictionKink.lua
Affliction | Version 2.0.5
-- Attempt to fix agony/corruption while moving, it's currently only applying them to surrounding targets while moving not spamming agony.
-- Fix(?) for soul rot not being cast during vile taint
Other stuff can't remmember :P
> Affliction | Version 2.0.5

- Rotations/Warlock/Affliction/AfflictionKink.lua
AfflictionKink | Version 2.0.6
-- Removed redundant code.
-- Added the following to the "Cooldowns" hotkey:
-- Trinkets
-- Racials
-- Covenant Ability
-- Malefic Rapture if we have at least 1 shard.
-- Added "Covenant TTD" config option in Offensives tab.
> AfflictionKink | Version 2.0.6

- Rotations/Warlock/Demonology/DemonologyKink.lua
Fix Demonic Tyrant not being summoned
> Fix Demonic Tyrant not being summoned

- Rotations/Warlock/Affliction/AfflictionKink.lua
> Lua error fix

- Rotations/Mage/Frost/FrostKink.lua
FrostKink | 1.2.4
-- (Fixed?) Mirrors of torment.
-- Possible fix for hard cast flurrys.
-- Old code removal/some corrections.
> FrostKink | 1.2.4

- Rotations/Mage/Frost/FrostKink.lua
FrostKink | Version 1.2.5
----------------------------------------
-- Added a "Pull OoC" setting so you can toggle whether or not the rotation initiates combat for you when solo.
> FrostKink | Version 1.2.5

- Rotations/Warlock/Affliction/AfflictionKink.lua
- System/Lists/Spells.lua
Affliction Memory leak fix | 2.1.1
Spells List for fire/etc updated.
> Affliction Memory leak fix | 2.1.1

- Rotations/Mage/Fire/KinkyFuego.lua
> KinkyFuego Beta Release

- Rotations/Warlock/Affliction/AfflictionKink.lua
Malefic Rapture fix? Version 2.1.3
> Malefic Rapture fix?

- Rotations/Mage/Fire/KinkyFuego.lua
Additional KinkyFuego Beta Changes.
> Additional KinkyFuego Beta Changes.

- Rotations/Mage/Fire/KinkyFuego.lua
KinkyFuego | Version 1.2.5
---------------------------------
-- Error fixes.
> KinkyFuego | Version 1.2.5

- Rotations/Mage/Fire/KinkyFuego.lua
-----------------------------------------
-- Added Predict Movement (Currently only coded for meteor, flamestrike is coming)
-- Added Meteor Target (Target or Best)
-- Added Ignore Meteor Targets during CDs
-- Changed filler spell to Fireball outside of Combustion. Removed 1 of the 3 scorch calls in combust filler for now.
> KinkyFuego | Version 1.2.7 | Beta

- Rotations/Mage/Frost/FrostKink.lua
FrostKink | Version 1.2.9
---------------------------------------
-- Fix (?) for targetUnit lua error.
> FrostKink | Version 1.2.9

- Rotations/Mage/Frost/FrostKink.lua
FrostKink | Version 1.2.6
-----------------------------------
-- Fix for targetUnit lua error.
> FrostKink | Version 1.2.6

- Rotations/Mage/Fire/KinkyFuego.lua
KinkyFuego | Version 1.2.9
-----------------------------------------
Penis
> KinkyFuego | Version 1.2.9

- Rotations/Mage/Frost/FrostKink.lua
FrostKink | Version 1.2.7
---------------------------------
-- General fixes/improvements.
---- Fix casting RoP/MI, etc on targets out of range/invalid.
---- Fix lua errors/targeting issues.
> FrostKink | Version 1.2.7

- System/Lists/Spells.lua
> Fire Spells List fix

- System/Lists/InterruptWhitelist.lua
updated to all importand interrupts in SL + torghast
> added all importand interrupts in SL

- README.md
- Rotations/Rogue/Assassination/AssaS0ul.lua
- Rotations/Rogue/Subtlety/SubS0ul.lua
- System/Lists/Spells.lua
- AssaS0ul3r dry written probably will need a lot of testing
- Sub and Assa got better necro support, coz simc sucks bis ballz
- fixes to spell lists in rogue section
- remove essences from Spells.lua
> Assassination by S0ul3r released, necro tweaks, spell list fixes, remove essences from Spells

- Rotations/Demon Hunter/Vengeance/VengeanceCuteOne.lua
- System/Lists/Spells.lua
- System/Lists/TankBusters.lua
VDH Update - Throw glaive aggro (beta), manual key for elysian decree, first pass of M+ stun/incap logic, imprison is now used an interrupt (if checked), tankbuster logic added.
> TCP - Updated Tankbuster List, Updated VDH

- Rotations/Demon Hunter/Vengeance/VengeanceCuteOne.lua
-- Removed Chaos Nova settings and Stun Logic
-- We can use Smart Queue for Elysian Decree mouseover
-- Tankbuster second pass to include fiery brand
> TCP - Silly Dev, VDH can't chaos nova

- Rotations/Warrior/Fury/WinterzFury.lua
- System/Lists/Spells.lua
- MT / ST Modes added
- Trinkets added
- Aftershock ST added
- Legendary support (cancelling BS etc) as soon as i get the legendary or someone with ALOT of time for testing :D
- looking for stormbolt logic in m+ (what do we want to stun?)
- maaaaaaybe fixed condemn?! nani?
> WinterzFury 1.1

- Rotations/Rogue/Assassination/AssaS0ul.lua
- Assassination opener fixes, 
- CT update to latest simC, 
- Crimson Tempest cast fixes
> Assassination opener fixes, update to latest simC, Crimson Tempest cast fixes

- Rotations/Warrior/Protection/Doparrior_Prot.lua
• Big optimizations and improvements on overall functionality of rotation.
• [Beta] Reprisal Key Support added
• Venthyr & Kyrian Cov support
• Improved shield block and IP logic
• and much more :)
> Update - Doparrior v1.1

- Rotations/Warrior/Protection/Doparrior_Prot.lua
• More kyrian support
• Spear of bastion fix - thnx laks :)
• Rotation optimization
• Don't aggro shades
• More aggressive, aggressive mode
> Doparrior - Prot v1.1.5

- Rotations/Rogue/Outlaw/OutLaks.lua
- System/Lists/CCUnits.lua
- System/Lists/InterruptWhitelist.lua
- Stuns work now, more feint casts, maybe better vanish for celerity
- Update stun list
- Update kick list
> Outlaw: working stuns, more feints, higher vanish prio

- Rotations/Rogue/Outlaw/OutLaks.lua
- System/Lists/CCUnits.lua
- System/Lists/Spells.lua
- Outlaw: fix for pausing when shades are up, better vanish with celerity
- Outlaw: Vanish with deathly shadows logic
- Outlaw: cleaner Trinkets
> Outlaw: DS logic, "hang" fixes, spells list cleanup

- Rotations/Rogue/Assassination/AssaS0ul.lua
- Hold shiv, 
- don't FoK in council, 
- additional prevention for Sire add
> Hold shiv, don't FoK in council, additional prevention for Sire add

- Rotations/Rogue/Outlaw/OutLaks.lua
- System/Lists/InterruptWhitelist.lua
- Skulker's tweak,
- bolts arent that important to kick (interrupt SUPERPALElist)
> Outlaw: Outlaw: Skulker's tweak, bolts arent that important to kick

- Rotations/Priest/Discipline/SnewyDisc.lua
Hello there 👋 
This is my first try of an up to date discipline priest rotation.
I'm looking forward to feedback 😄
Cheers Snewy
> Initial discipline priest rotation

- Rotations/Rogue/Assassination/AssaS0ul.lua
- Rotations/Rogue/Outlaw/OutLaks.lua
- Rotations/Rogue/Subtlety/SubS0ul.lua
- Assa: added vessel, sbs fix for spread
- Sub: sbs fix for spread
- Outlaw: sbs fix for spread
> Sbs spread fix, trinket for assa

- Rotations/Rogue/Outlaw/OutLaks.lua
- DS after vanish use dispatch instead of ambush
> Outlaw: DS after vanish use dispatch instead of ambush

- Rotations/Priest/Discipline/SnewyDisc.lua
- Rotations/Priest/Shadow/SnewyShadow.lua
- System/Lists/Pets.lua
- System/Lists/Spells.lua
* Minor discipline priest rotation improvements
* Initial shadow priest rotation
> Priest Extensions

- Rotations/Rogue/Assassination/AssaS0ul.lua
- Rotations/Rogue/Outlaw/OutLaks.lua
- Rotations/Rogue/Subtlety/SubS0ul.lua
- Assa: SBS logic for shades, less SnD
- Sub: SBS logic for shades
- Outlul: SBS logic for shades, added Dreadfire Vessel
> Rogue tweaks

- Rotations/Hunter/Survival/SurvivalCuteOne.lua
Was missing module.BasicTrinkets()
Not sure where best to put it
> Added trinkets usage on survival hunter

- Rotations/Hunter/Survival/PoncheSurvival.lua
- System/Lists/Spells.lua
- Kill Shot hp check
- Coordinated Assault AOE
- Pheromone Bomb
> PoncheSurvival fix

- Rotations/Hunter/Survival/PoncheSurvival.lua
- System/Lists/Spells.lua
- Fixed Mad Bombardier buff id
- M+ CC Helper (Thx to BigMarksmanship.lua)
- Some small improvements
> PoncheSurvival update

- Rotations/Hunter/Survival/PoncheSurvival.lua
-Fixed inverted CC modes
-Single target mode fix
> Updated PoncheSurvival.lua

- Rotations/Shaman/Enhancement/EnhancementbecyTR.lua
1) Adjusted Primordial Wave usage.
2) Fixed Fae Transfusion usage in aoe.
3) Set some ui default values.
4) Added weapon imbue, shield checks to combat part.
5) Removed TTD check from Feral Spirits.
> Enhancement Shaman

- Rotations/Hunter/Marksmanship/MarksmanshipCuteOne.lua
Fixed spelling error on line 600.
Checking for Buff trueshot
> Fixed Spelling in MarksmanshipCuteOne

- Rotations/Hunter/Survival/PoncheSurvival.lua
Stole blacklist from Lak's resto shaman + added Necrotic Wake and Tazavesh bosses. Added logic to Freezing Trap and Intimidation.
> Add stun blacklist for survival hunter CC

- .github/update_readme.py
Adds rudimentary but effective MD and HTML sanitization. Truncates user-provided inputs to maximum lengths. Fixed formatting.
> Sanitize README Bot inputs.

- Rotations/Druid/Feral/FeralCuteOne.lua
Lunar Inspiration talent check when using moonfire and primalWrath fix
> Lunar Inspiration and primalWrath fix

- Rotations/Monk/Mistweaver/Sinweaving.lua
- System/Lists/Spells.lua
1.0.1
-     Added support for **Faeline Stomp** (MW Talent)
-     Added support for **Zen Pulse** (MW Talent)
-     Added support for **Vivacious Vivification** (Monk Talent)
-     ____ Be able to cast **Vivify** when you have the VV buff and **are(or not) moving**
-     Fix 5P/20P Mode Icon (again)
1.0.2
-     Fix **Vivify** during **Vivacious Vivification** in combinaision w/ **Thunder Focus Tea**
> Sinweaving 1.0.2

- Rotations/Hunter/Survival/SurvivalCuteOne.lua
- Rotations/Paladin/Holy/Nessaj.lua
- System/Lists/Spells.lua
added breaking dawn for holy paladin
disabled a few serpent stings and added explosive shot to single target for survival hunter
> minor updates

- System/Lists/Spells.lua
Soul reaper changed to a tier 10 core DK ability, put it in shared spell section (if that works for you)
> Soul Reaper

- Rotations/Monk/WindWalker/BrewWindWalker.lua
currently supports up to level 57 PVE Monk
> Initial Monk WW

- Rotations/Monk/WindWalker/BrewWindWalker.lua
- System/Lists/Items.lua
- System/Lists/Spells.lua
100% coverage of PVE Levelling, Not Raid/Dungeon ready.
> Update to WW Rotation

- Rotations/Death Knight/Blood/BrewBloodKnightSC.lua
- Rotations/Monk/BrewMaster/BrewBrewMaster.lua
- System/API/Use.lua
- System/Lists/Items.lua
- System/Lists/Spells.lua
Updated Use, Also added a DK Blood pure SimC rotation that focuses on DPS
> ability to use best of list and check usability of best of list

- Rotations/Death Knight/Unholy/BrewUnholyDK.lua
- System/API/Module.lua
- System/Lists/Items.lua
- System/Lists/Spells.lua
Added DKUnholy spec routine
Added module.VariablePhial and module.variableCombatPotion
> +DKUnholy, Module Update for variable Phials/Pots

- System/engines/HealingEngineFunctions.lua
Opening a PR on this because it's a core file.
> Fix to cast at location

- Rotations/Monk/MistWeaver/BrewMistweaver.lua
added priority support for Teachings of the monastery and ancient teachings.  Added option to roll automatically, changed code for jade statue to use object manager to look for objects you've placed rather than a hack that just tracks the last place you cast it.
> Updated Misweaver

- Rotations/Monk/MistWeaver/BrewMistweaver.lua
- System/API/Module.lua
- System/API/Unit.lua
- System/Functions/Custom.lua
- System/Lists/Items.lua
- System/Lists/Spells.lua
added core module functionality to support Phials and Runes. Use it the same way you FlaskUP([section])
PhialUP([section]) or ImbueUp([section])
> Added full module support for Phials and Rune
